### PR TITLE
Packaging improvements

### PR DESCRIPTION
**Pull request by kynan**
- Add MANIFEST.in to keep source dist "clean"
- Use `build` to build source dist and wheel

### CODE REVIEW

**Comment by mcarans** [comment]
@mccalluc Any chance of merging this PR which blocks some usages of Frictionless via conda-forge?

**Comment by kynan** [comment]
@mccalluc Anything holding this back?

**Comment by mcarans** [comment]
@yuanzhou Sorry to bother you, but it looks like mccalluc is no longer around so wondering if it would be possible for you to look at this?

**Comment by yuanzhou** [comment]
> @yuanzhou Sorry to bother you, but it looks like mccalluc is no longer around so wondering if it would be possible for you to look at this?

@mcarans I personally never realized the existence of this repo. Could we use some help from @john-conroy?

**Comment by john-conroy** [comment]
We're not sure who will be maintaining this project in the future, but I'm working towards helping you resolve this PR and get a new version published. I believe #29 should fix #28.

**Comment by kynan** [comment]
@john-conroy *this* PR will *also* address #28 and is the recommended approach :)

`setup.py` is deprecated and you should ideally migrate away from it.

**Comment by kynan** [comment]
And it appears simply using `python3 -m build` already does the right thing even without a `MANIFEST.in`. No change to `setup.py` needed...

**Pull request merged**
